/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
  kPIN_MUX_DirectionInput = 0U,         /* Input direction */
  kPIN_MUX_DirectionOutput = 1U,        /* Output direction */
  kPIN_MUX_DirectionInputOrOutput = 2U  /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);


/*!
 * @brief 
 *
 */
void WDOG_B(void);


/*!
 * @brief 
 *
 */
void qspiFlash(void);


/*!
 * @brief 
 *
 */
void SDRAM(void);

/* WAKEUP (coord L6), WEKAUP */
#define SNVS_WAKEUP_GPIO                                                   GPIO5   /*!< GPIO device name: GPIO5 */
#define SNVS_WAKEUP_PORT                                                   GPIO5   /*!< PORT device name: GPIO5 */
#define SNVS_WAKEUP_PIN                                                       0U   /*!< GPIO5 pin index: 0 */

/* PMIC_STBY_REQ (coord L7), PMIC_STBY */
#define SNVS_PMIC_STBY_GPIO                                                GPIO5   /*!< GPIO device name: GPIO5 */
#define SNVS_PMIC_STBY_PORT                                                GPIO5   /*!< PORT device name: GPIO5 */
#define SNVS_PMIC_STBY_PIN                                                    2U   /*!< GPIO5 pin index: 2 */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void SNVS(void);

/* GPIO_SD_B0_03 (coord K1), D1 */
#define SD_D1_PERIPHERAL                                                  USDHC1   /*!< Device name: USDHC1 */
#define SD_D1_SIGNAL                                                  usdhc_data   /*!< USDHC1 signal: usdhc_data */
#define SD_D1_CHANNEL                                                         1U   /*!< USDHC1 usdhc_data channel: 1 */

/* GPIO_SD_B0_02 (coord J1), D0 */
#define SD_D0_PERIPHERAL                                                  USDHC1   /*!< Device name: USDHC1 */
#define SD_D0_SIGNAL                                                  usdhc_data   /*!< USDHC1 signal: usdhc_data */
#define SD_D0_CHANNEL                                                         0U   /*!< USDHC1 usdhc_data channel: 0 */

/* GPIO_SD_B0_01 (coord J3), CLK */
#define SD_CLK_PERIPHERAL                                                 USDHC1   /*!< Device name: USDHC1 */
#define SD_CLK_SIGNAL                                                  usdhc_clk   /*!< USDHC1 signal: usdhc_clk */

/* GPIO_SD_B0_00 (coord J4), CMD */
#define SD_CMD_PERIPHERAL                                                 USDHC1   /*!< Device name: USDHC1 */
#define SD_CMD_SIGNAL                                                  usdhc_cmd   /*!< USDHC1 signal: usdhc_cmd */

/* GPIO_SD_B0_04 (coord H2), D2 */
#define SD_D2_PERIPHERAL                                                  USDHC1   /*!< Device name: USDHC1 */
#define SD_D2_SIGNAL                                                  usdhc_data   /*!< USDHC1 signal: usdhc_data */
#define SD_D2_CHANNEL                                                         2U   /*!< USDHC1 usdhc_data channel: 2 */

/* GPIO_SD_B0_05 (coord J2), D3 */
#define SD_D3_PERIPHERAL                                                  USDHC1   /*!< Device name: USDHC1 */
#define SD_D3_SIGNAL                                                  usdhc_data   /*!< USDHC1 signal: usdhc_data */
#define SD_D3_CHANNEL                                                         3U   /*!< USDHC1 usdhc_data channel: 3 */

/* GPIO_B1_12 (coord D13), CD */
#define SD_CD_GPIO                                                         GPIO2   /*!< GPIO device name: GPIO2 */
#define SD_CD_PORT                                                         GPIO2   /*!< PORT device name: GPIO2 */
#define SD_CD_PIN                                                            28U   /*!< GPIO2 pin index: 28 */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void SD(void);


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void camera(void);

/* GPIO_B0_00 (coord D7), D0 */
#define LCD_D0_GPIO                                                        GPIO2   /*!< GPIO device name: GPIO2 */
#define LCD_D0_PORT                                                        GPIO2   /*!< PORT device name: GPIO2 */
#define LCD_D0_PIN                                                            0U   /*!< GPIO2 pin index: 0 */

/* GPIO_B0_01 (coord E7), D1 */
#define LCD_D1_GPIO                                                        GPIO2   /*!< GPIO device name: GPIO2 */
#define LCD_D1_PORT                                                        GPIO2   /*!< PORT device name: GPIO2 */
#define LCD_D1_PIN                                                            1U   /*!< GPIO2 pin index: 1 */

/* GPIO_B0_02 (coord E8), D2 */
#define LCD_D2_GPIO                                                        GPIO2   /*!< GPIO device name: GPIO2 */
#define LCD_D2_PORT                                                        GPIO2   /*!< PORT device name: GPIO2 */
#define LCD_D2_PIN                                                            2U   /*!< GPIO2 pin index: 2 */

/* GPIO_B0_03 (coord D8), D3 */
#define LCD_D3_GPIO                                                        GPIO2   /*!< GPIO device name: GPIO2 */
#define LCD_D3_PORT                                                        GPIO2   /*!< PORT device name: GPIO2 */
#define LCD_D3_PIN                                                            3U   /*!< GPIO2 pin index: 3 */

/* GPIO_B0_04 (coord C8), BT_CFG0/PD */
#define LCD_D4_GPIO                                                        GPIO2   /*!< GPIO device name: GPIO2 */
#define LCD_D4_PORT                                                        GPIO2   /*!< PORT device name: GPIO2 */
#define LCD_D4_PIN                                                            4U   /*!< GPIO2 pin index: 4 */

/* GPIO_B0_05 (coord B8), BT_CFG1/PD */
#define LCD_D5_GPIO                                                        GPIO2   /*!< GPIO device name: GPIO2 */
#define LCD_D5_PORT                                                        GPIO2   /*!< PORT device name: GPIO2 */
#define LCD_D5_PIN                                                            5U   /*!< GPIO2 pin index: 5 */

/* GPIO_B0_06 (coord A8), BT_CFG2/PD */
#define LCD_D6_GPIO                                                        GPIO2   /*!< GPIO device name: GPIO2 */
#define LCD_D6_PORT                                                        GPIO2   /*!< PORT device name: GPIO2 */
#define LCD_D6_PIN                                                            6U   /*!< GPIO2 pin index: 6 */

/* GPIO_B0_07 (coord A9), BT_CFG3/PD */
#define LCD_D7_GPIO                                                        GPIO2   /*!< GPIO device name: GPIO2 */
#define LCD_D7_PORT                                                        GPIO2   /*!< PORT device name: GPIO2 */
#define LCD_D7_PIN                                                            7U   /*!< GPIO2 pin index: 7 */

/* GPIO_B0_12 (coord C10), BT_CFG8/PD */
#define LCD_WR_GPIO                                                        GPIO2   /*!< GPIO device name: GPIO2 */
#define LCD_WR_PORT                                                        GPIO2   /*!< PORT device name: GPIO2 */
#define LCD_WR_PIN                                                           12U   /*!< GPIO2 pin index: 12 */

/* GPIO_B0_13 (coord D10), BT_CFG9/PD */
#define LCD_DC_GPIO                                                        GPIO2   /*!< GPIO device name: GPIO2 */
#define LCD_DC_PORT                                                        GPIO2   /*!< PORT device name: GPIO2 */
#define LCD_DC_PIN                                                           13U   /*!< GPIO2 pin index: 13 */

/* GPIO_B1_08 (coord A12), keyboard/C0 */
#define LCD_C0_GPIO                                                        GPIO2   /*!< GPIO device name: GPIO2 */
#define LCD_C0_PORT                                                        GPIO2   /*!< PORT device name: GPIO2 */
#define LCD_C0_PIN                                                           24U   /*!< GPIO2 pin index: 24 */

/* GPIO_B1_09 (coord A13), keyboard/C1 */
#define LCD_C1_GPIO                                                        GPIO2   /*!< GPIO device name: GPIO2 */
#define LCD_C1_PORT                                                        GPIO2   /*!< PORT device name: GPIO2 */
#define LCD_C1_PIN                                                           25U   /*!< GPIO2 pin index: 25 */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void LCD(void);


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void SWD(void);


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void ENC(void);


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void UART(void);


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void SPI(void);

/* GPIO_SD_B1_04 (coord P2), SCL */
#define IIC_SCL_PERIPHERAL                                                LPI2C1   /*!< Device name: LPI2C1 */
#define IIC_SCL_SIGNAL                                                       SCL   /*!< LPI2C1 signal: SCL */

/* GPIO_SD_B1_05 (coord N3), SDA */
#define IIC_SDA_PERIPHERAL                                                LPI2C1   /*!< Device name: LPI2C1 */
#define IIC_SDA_SIGNAL                                                       SDA   /*!< LPI2C1 signal: SDA */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void IIC(void);

/* GPIO_AD_B0_08 (coord F13), keyboard JTAG_MOD/JTAG_MOD/PD */
#define GPIO_BEE_GPIO                                                      GPIO1   /*!< GPIO device name: GPIO1 */
#define GPIO_BEE_PORT                                                      GPIO1   /*!< PORT device name: GPIO1 */
#define GPIO_BEE_PIN                                                          8U   /*!< GPIO1 pin index: 8 */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void GPIO(void);

/* GPIO_B1_10 (coord B13), keyboard/OE_B */
#define PWM_OE_B_GPIO                                                      GPIO2   /*!< GPIO device name: GPIO2 */
#define PWM_OE_B_PORT                                                      GPIO2   /*!< PORT device name: GPIO2 */
#define PWM_OE_B_PIN                                                         26U   /*!< GPIO2 pin index: 26 */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void PWM(void);


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void ADC(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
